/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

interface Props {
    scale?: number
    position?: [number, number, number]
    rotation?: [number, number, number]
}
 function WizardHat(props: Props) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { nodes, materials } = useGLTF('/WizardHat.glb') as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials['Material.001']}
        position={[0, 0.983, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.star.geometry}
        material={materials.star}
        position={[0.44, 1.075, -0.29]}
        rotation={[0.563, -0.867, 2.379]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.star001.geometry}
        material={materials.star}
        position={[0.44, 1.075, 0.448]}
        rotation={[3.072, -1.13, 1.816]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.star002.geometry}
        material={materials.star}
        position={[-0.562, 1.075, -0.282]}
        rotation={[3.072, -1.13, 1.816]}
        scale={-0.043}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.star003.geometry}
        material={materials.star}
        position={[-0.562, 1.075, 0.439]}
        rotation={[2.488, 0.922, 1.912]}
        scale={-0.043}
      />
    </group>
  )
}

useGLTF.preload('/WizardHat.glb');

export default WizardHat;